# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='section',
            field=models.CharField(default=' ', max_length=1024, verbose_name='\u0418\u043d\u0442\u0435\u0440\u0435\u0441\u0443\u044e\u0449\u0438\u0439 \u0440\u0430\u0437\u0434\u0435\u043b'),
            preserve_default=False,
        ),
    ]
