# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160126_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='section',
        ),
        migrations.AddField(
            model_name='order',
            name='page',
            field=models.CharField(default='', max_length=1024, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
            preserve_default=False,
        ),
    ]
