# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 10:26
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='about',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
