# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160126_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='utm',
            field=models.SlugField(max_length=255, unique=True, verbose_name='UTM \u043c\u0435\u0442\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='utm',
            field=models.SlugField(max_length=255, unique=True, verbose_name='UTM \u043c\u0435\u0442\u043a\u0430'),
        ),
    ]
