# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20160131_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='\u0418\u041c\u042f'),
        ),
    ]
