# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-22 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20171222_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price_from',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0442'),
        ),
        migrations.AlterField(
            model_name='category',
            name='price_to',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0434\u043e'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_from',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0442'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_to',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0434\u043e'),
        ),
    ]
