# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20171222_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price_to',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_to',
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
