# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20180113_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='META description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='META keywords'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='META description'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='META keywords'),
        ),
    ]
